### PR TITLE
adjusted the view button to be suitable with filters applied to a table 

### PR DESCRIPTION
**Pull request by ahmed3alali**
### Before:

Screenshot 2024-11-06 at 19 51 41

### After:

Screenshot 2024-11-06 at 20 12 06

## Types of changes

Took the view button to the most left, a more suitable view for a better UX where filters appear at the bottom and the view button at the top of them aligned in the same line

### CODE REVIEW

**Comment by a0m0rajab** [comment]
Thanks for the PR, we are expecting a different style, something like the next image: 

image

**Review by a0m0rajab — CHANGES_REQUESTED** [review]
.

**Comment by ahmed3alali** [comment]
I am working on the task

**Comment by a0m0rajab** [comment]
Closing this PR due inactivity

**Pull request closed without merging**
